config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'memos#index'
  # resources :memos  
  resources :memos
  resources :mmemos
  resources :dmemos
  resources :users, only:[:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dmemo.rb
class Dmemo < ApplicationRecord
  validates :deadline, presence: true
  validates :comment,  presence: true

  belongs_to :user
end

app/models/memo.rb
class Memo < ApplicationRecord
  # validates :deadline, presence: true
  validates :time, presence: true
  validates :comment, presence: true

  belongs_to :user
end

app/models/mmemo.rb
class Mmemo < ApplicationRecord
  validates :deadline, presence: true
  validates :comment,  presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :memos
  has_many :mmemos
  has_many :dmemos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/dmemos_controller.rb
class DmemosController < ApplicationController

  before_action :correct_user, except: [:index, :new, :create]
  
  def new
    @dmemo = Dmemo.new
  end

  def create
    dmemo = Dmemo.create(dmemo_params)
    if dmemo.save
      flash[:memo] = 'メモを作成しました。'
      redirect_to root_path
    else
      flash[:memo] = '入力項目を入力してください。'
      redirect_to new_dmemo_path
    end
  end

  def show
    @dmemo = Dmemo.find(params[:id])
  end

  def edit
    @dmemo = Dmemo.find(params[:id])  
  end

  def update
    dmemo = Dmemo.find(params[:id])
    if dmemo.update(dmemo_params)
      flash[:memo] = 'メモを更新しました。'
      redirect_to root_path
    else
      flash[:memo] = '入力項目を入力してください。'
      redirect_to edit_dmemo_path
    end
  end

  def destroy
    dmemo = Dmemo.find(params[:id])
    if dmemo.destroy
      flash[:memo] = 'メモを削除しました。'
      redirect_to root_path
    else
      flash[:memo] = 'メモを削除出来ませんでした。'
      redirect_to root_path
    end
  end


  private

  def dmemo_params
    params.require(:dmemo).permit(:deadline,:comment).merge(user_id: current_user.id)
  end

  def correct_user
    @dmemo = current_user.dmemos.find_by(id: params[:id])
      unless @dmemo
        flash[:memo] = '他ユーザーの情報へはアクセス出来ません。'
        redirect_to root_path
      end
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  before_action :correct_user, except: [:index, :new, :create]

  def index
    @memos = Memo.all
    @mmemos = Mmemo.all
    @dmemos = Dmemo.all
  end

  def new
    @memo = Memo.new
  end

  def create
    memo = Memo.create(memo_params)
    if memo.save
      flash[:memo] = 'メモを作成しました。'
      redirect_to root_path
    else
      flash[:memo] = '入力項目を入力してください。'
      redirect_to new_memo_path
    end
  end

  def show
    @memo = Memo.find(params[:id])
  end

  def edit
    @memo = Memo.find(params[:id])
  end

  def update
    memo = Memo.find(params[:id])
    if memo.update(memo_params)
      flash[:memo] = 'メモを更新しました。'
      redirect_to root_path
    else
      flash[:memo] = '入力項目を入力してください。'
      redirect_to  edit_memo_path
    end
  end

  def destroy
    memo = Memo.find(params[:id])
    if memo.destroy
      flash[:memo] = 'メモを削除しました。'
      redirect_to root_path
    else
      flash[:memo] = 'メモを削除出来せんでした。'
      redirect_to root_path
    end
  end
  

  private 

  def memo_params
    params.require(:memo) .permit(:deadline,:time,:comment).merge(user_id: current_user.id)
  end
  
  def correct_user
    @memo = current_user.memos.find_by(id: params[:id])
    unless @memo
      flash[:memo] = '他ユーザーの情報へはアクセス出来ません。'
      redirect_to root_path
    end
  end

end

app/controllers/mmemos_controller.rb
class MmemosController < ApplicationController
  
  before_action :correct_user, except: [:index, :new, :create]

  def new
    @mmemo = Mmemo.new
  end

  def create
    mmemo = Mmemo.create(mmemo_params)
    if mmemo.save
      flash[:memo] = 'メモを作成しました。'
      redirect_to root_path
    else
      flash[:memo] = '入力項目を入力してください。'
      redirect_to new_mmemo_path
    end
  end

  def show
    @mmemo = Mmemo.find(params[:id])
  end

  def edit
    @mmemo =Mmemo.find(params[:id])
  end

  def update
    mmemo = Mmemo.find(params[:id])
    if mmemo.update(mmemo_params)
      flash[:memo] = 'メモを更新しました。'
      redirect_to root_path
    else
      flash[:memo] = '入力項目を入力してください。'
      redirect_to edit_mmemo_path
    end
  end

  def destroy
    mmemo = Mmemo.find(params[:id])
    if mmemo.destroy
      flash[:memo] = 'メモを削除しました。'
      redirect_to root_path
    else
      flash[:memo] = 'メモを削除出来ませんでした。'
      redirect_to root_path
    end
  end


  private

  def mmemo_params
    params.require(:mmemo).permit(:deadline,:comment).merge(user_id: current_user.id)
  end

  def correct_user
    @mmemo = current_user.mmemos.find_by(id: params[:id])
    unless @mmemo
      flash[:memo] = '他ユーザーの情報へはアクセス出来ません。'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dmemos_helper.rb
module DmemosHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/mmemos_helper.rb
module MmemosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dmemos/edit.html.haml
= render "memos/header"
.new-memo-body
  .new-memo-main
    .new-memo-main__title
      更新ページ（短期の予定）
    =form_with model: @dmemo, class:"new-form" ,local: true do |dm|
      .new-form__timebox
        .new-form__timebox__letter
          期　限　：
        =dm.text_field :deadline, class:"new-form__timebox__time",placeholder:"  入力してください。"
      .new-form__commentbox
        .new-form__commentbox__letter
          行う事　：    
        =dm.text_area :comment, class:"new-form__commentbox__comment", placeholder:"  入力してください。"
      =dm.submit "更新する",class:"new-form__submit"

app/views/dmemos/new.html.haml
= render "memos/header"
.new-memo-body
  .new-memo-main
    .new-memo-main__title
      新規登録ページ（短期の予定）
    =form_with model: @dmemo, class:"new-form" ,local: true do |dm|
      .new-form__timebox
        .new-form__timebox__letter
          期　限　：
        =dm.text_field :deadline, class:"new-form__timebox__time",placeholder:"  入力してください。"
      .new-form__commentbox
        .new-form__commentbox__letter
          行う事　：    
        =dm.text_area :comment, class:"new-form__commentbox__comment", placeholder:"  入力してください。"
      =dm.submit "投稿する",class:"new-form__submit"

app/views/dmemos/show.html.haml
= render "memos/header"
.show-memo-body
  .show-memo-main
    .show-memo-main__title
      詳細ページ（短期な予定）
    .show-form
      .show-form__timebox
        .show-form__timebox__letter
          期　限　：
        .show-form__timebox__time
          = @dmemo.deadline
      .show-form__commentbox
        .show-form__commentbox__letter        
          行う事　：
        .show-form__commentbox__comment
          = @dmemo.comment 
      .show-form__submit
        =link_to '編集',edit_dmemo_path,class: 'show-form__submit__link'

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Memoapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/memos/_header.html.haml
.header
  .header__main
    .header__main__top
      = link_to image_tag('/images/rogo.png', class: 'rogo'), root_path

    .header__main__under

app/views/memos/edit.html.haml
= render "header"
.new-memo-body
  .new-memo-main
    .new-memo-main__title
      更新ページ（日々のルーティング）
    =form_with model: @memo, class:"new-form" ,local: true do |m|
      .new-form__timebox
        .new-form__timebox__letter
          開始時間：
        =m.text_field :time, class:"new-form__timebox__time",placeholder:"  入力してください。"
      .new-form__commentbox
        .new-form__commentbox__letter
          行う事　：    
        =m.text_area :comment, class:"new-form__commentbox__comment", placeholder:"  入力してください。"
      =m.submit "更新する",class:"new-form__submit"

app/views/memos/index.html.haml
= render "header"
.user
  .user__letter-name
    .user__letter-name__letter
      ユーザー名：
    .user__letter-name__name
      = current_user.name
  .user__edit
    = link_to'編集',edit_user_path(current_user),class:'user-edit' 
  .user__delete
    = link_to'ログアウト',destroy_user_session_path,method: :delete,class:'user-delete'

.main
  .main__routing-ber
    .main__routing-ber__letter-link
      .main__routing-ber__letter-link__letter
        日々のルーティング
      .main__routing-ber__letter-link__link
        = link_to '新規投稿',new_memo_path, class:'routing-new' 
    - @memos.each do |m|
      -if user_signed_in? && m.user_id == current_user.id 
        .main__routing-ber__boxtop
          .main__routing-ber__box
            .main__routing-ber__box__time-todo
              .main__routing-ber__box__time-todo__deadline
              .main__routing-ber__box__time-todo__time
                時　間：
                = m.time.truncate(15)
              .main__routing-ber__box__time-todo__todo
                行う事：
                = m.comment.truncate(15)
            .main__routing-ber__box__edit-delete
              .main__routing-ber__box__edit-delete__detailbtn
                = link_to '詳細',memo_path(m.id), class:'routing-detail' 
              .main__routing-ber__box__edit-delete__editbtn
                = link_to '編集',edit_memo_path(m.id), class:'routing-edit' 
              .main__routing-ber__box__edit-delete__deletebtn
                = link_to '削除',memo_path(m.id), method: :delete, class:'routing-delete', data: { confirm: "本当にコメントを削除してもよろしいですか？" }

    
  .main__month-day
    .main__month-day__month-ber
      .main__month-day__month-ber__letter-link
        .main__month-day__month-ber__letter-link__letter
          長期の予定
        .main__month-day__month-ber__letter-link__link
          = link_to '新規投稿',new_mmemo_path, class:'month-new'
      - @mmemos.each do |mm|
        -if user_signed_in? && mm.user_id == current_user.id 
          .main__month-day__month-ber__boxtop
            .main__month-day__month-ber__box
              .main__month-day__month-ber__box__detailbtn-todo       
                .main__month-day__month-ber__box__detailbtn-todo__detailbtn
                  期　限：
                  = mm.deadline.truncate(25)
                .main__month-day__month-ber__box__detailbtn-todo__todo
                  行う事：
                  = mm.comment.truncate(25)
              .main__month-day__month-ber__box__edit-delete
                .main__month-day__month-ber__box__edit-delete__detailbtn
                  = link_to '詳細',mmemo_path(mm.id), class:'month-detail'  
                .main__month-day__month-ber__box__edit-delete__editbtn  
                  = link_to '編集',edit_mmemo_path(mm.id), class:'month-edit'  
                .main__month-day__month-ber__box__edit-delete__deletebtn
                  = link_to '削除',mmemo_path(mm.id),method: :delete,class:'month-delete', data: { confirm: "本当にコメントを削除してもよろしいですか？" }

    .main__month-day__today-ber
      .main__month-day__today-ber__letter-link
        .main__month-day__today-ber__letter-link__letter
          短期の予定
        .main__month-day__today-ber__letter-link__link
          = link_to '新規投稿',new_dmemo_path, class:'today-new'

      - @dmemos.each do |dm|  
        -if user_signed_in? && dm.user_id == current_user.id 
          .main__month-day__today-ber__boxtop   
            .main__month-day__today-ber__box
              .main__month-day__today-ber__box__detailbtn-todo           
                .main__month-day__today-ber__box__detailbtn-todo__detailbtn
                  期　限：
                  = dm.deadline.truncate(25)
                .main__month-day__today-ber__box__detailbtn-todo__todo
                  行う事：
                  = dm.comment.truncate(25)
              .main__month-day__today-ber__box__edit-delete
                .main__month-day__today-ber__box__edit-delete__detailbtn
                  = link_to '詳細',dmemo_path(dm.id), class:'today-detail'
                .main__month-day__today-ber__box__edit-delete__editbtn  
                  = link_to '編集',edit_dmemo_path(dm.id), class:'today-edit'   
                .main__month-day__today-ber__box__edit-delete__deletebtn
                  = link_to '削除',dmemo_path(dm.id),method: :delete, class:'today-delete', data: { confirm: "本当にコメントを削除してもよろしいですか？" }
            

app/views/memos/new.html.haml
= render "header"
.new-memo-body
  .new-memo-main
    .new-memo-main__title
      新規登録ページ（日々のルーティング）
    =form_with model: @memo, class:"new-form" ,local: true do |r|
      .new-form__timebox
        .new-form__timebox__letter
          開始時間：
        =r.text_field :time, class:"new-form__timebox__time",placeholder:"  入力してください。"
      .new-form__commentbox
        .new-form__commentbox__letter
          行う事　：    
        =r.text_area :comment, class:"new-form__commentbox__comment", placeholder:"  入力してください。"
      =r.submit "投稿する",class:"new-form__submit"

app/views/memos/show.html.haml
= render "header"
.show-memo-body
  .show-memo-main
    .show-memo-main__title
      詳細ページ（日々のルーティング）
    .show-form
      .show-form__timebox
        .show-form__timebox__letter
          開始時間：
        .show-form__timebox__time
          = @memo.time
      .show-form__commentbox
        .show-form__commentbox__letter        
          行う事　：
        .show-form__commentbox__comment
          = @memo.comment 
      .show-form__submit
        =link_to '編集',edit_memo_path,class: 'show-form__submit__link'

app/views/mmemos/edit.html.haml
= render "memos/header"
.new-memo-body
  .new-memo-main
    .new-memo-main__title
      更新ページ（長期の予定）
    =form_with model: @mmemo, class:"new-form" ,local: true do |mm|
      .new-form__timebox
        .new-form__timebox__letter
          期　限　：
        =mm.text_field :deadline, class:"new-form__timebox__time",placeholder:"  入力してください。"
      .new-form__commentbox
        .new-form__commentbox__letter
          行う事　：    
        =mm.text_area :comment, class:"new-form__commentbox__comment", placeholder:"  入力してください。"
      =mm.submit "更新する",class:"new-form__submit"

app/views/mmemos/new.html.haml
= render "memos/header"
.new-memo-body
  .new-memo-main
    .new-memo-main__title
      新規登録ページ（長期の予定）
    =form_with model: @mmemo, class:"new-form" ,local: true do |mm|
      .new-form__timebox
        .new-form__timebox__letter
          期　限　：
        =mm.text_field :deadline, class:"new-form__timebox__time",placeholder:"  入力してください。"
      .new-form__commentbox
        .new-form__commentbox__letter
          行う事　：    
        =mm.text_area :comment, class:"new-form__commentbox__comment", placeholder:"  入力してください。"
      =mm.submit "投稿する",class:"new-form__submit"

app/views/mmemos/show.html.haml
= render "memos/header"
.show-memo-body
  .show-memo-main
    .show-memo-main__title
      詳細ページ（長期な予定）
    .show-form
      .show-form__timebox
        .show-form__timebox__letter
          期　限　：
        .show-form__timebox__time
          = @mmemo.deadline
      .show-form__commentbox
        .show-form__commentbox__letter        
          行う事　：
        .show-form__commentbox__comment
          = @mmemo.comment 
      .show-form__submit
        =link_to '編集',edit_mmemo_path,class: 'show-form__submit__link'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト",destroy_user_session_path,method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'